import json

# Load the response JSON generated by the LLM
with open("response.json", "r", encoding="utf-8") as f:
    response_data = json.load(f)

# The actual receipt payload is stored as a JSON string inside the LLM response
content_str = response_data["choices"][0]["message"]["content"]

# Parse the JSON string into a Python dict
receipt = json.loads(content_str)


# [FOR OUTPUT TESTING]
# Extract individual fields
# merchant = receipt.get("merchant")
# date = receipt.get("date")
# items = receipt.get("items", [])
# tax = receipt.get("tax")
# total = receipt.get("total")
# category = receipt.get("category")

# the extracted information
# print("=== Extracted Receipt Information ===")
# print(f"Merchant : {merchant}")
# print(f"Date     : {date}")
# print(f"Tax      : {tax}")
# print(f"Total    : {total}")
# print(f"Category : {category}")

# print("\nItems:")
# for i, item in enumerate(items, start=1):
#     name = item.get("name")
#     price = item.get("price")
#     print(f"  {i}. {name} – {price}")